### ISSUE TITLE
Getting Started Error "No module named functools_lru_cache"

### ISSUE THREAD

**Issue by holzhannes** [systemli/userli#292]
## Problem

Following the [getting started guide](https://systemli.github.io/userli/getting-started/) on Debian Buster at `sudo molecule converge -s localhost` the following error is occurring:
```
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 6, in <module>
    from molecule.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/molecule/__main__.py", line 22, in <module>
    from molecule.shell import main
  File "/usr/local/lib/python2.7/dist-packages/molecule/shell.py", line 31, in <module>
    from molecule import command
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/__init__.py", line 27, in <module>
    from molecule.command import base  # noqa
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/base.py", line 31, in <module>
    import molecule.scenarios
  File "/usr/local/lib/python2.7/dist-packages/molecule/scenarios.py", line 27, in <module>
    from molecule import util
  File "/usr/local/lib/python2.7/dist-packages/molecule/util.py", line 47, in <module>
    from backports.functools_lru_cache import lru_cache  # noqa
ImportError: No module named functools_lru_cache
```
## Possible solution
In this [Issue](https://github.com/matplotlib/matplotlib/issues/9344#issuecomment-469324522) the solution is stated, just run the following: `sudo apt install python-backports.functools-lru-cache`

**Comment by t2d** [comment]
Thank you for figuring that out. Can you provide a PR for the docs?
